##version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver --settings=vul.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1