version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1