# Generated by Django 3.2.25 on 2025-01-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('source_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('vuln_status', models.CharField(blank=True, max_length=50, null=True)),
                ('Bseverity', models.CharField(blank=True, choices=[('HIGHT', 'HIGHT'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('FIXED', 'FIXED'), ('REJECTED', 'REJECTED')], max_length=20, null=True)),
            ],
        ),
    ]
